---
delegatebot:
  watch:
  - target: { channel: &cf-docs C03B0T0D5 }
  delegate: &interrupts
    union:
    - if:
        when:
        - hours: { tz: America/Los_Angeles, start: 09:00, end: 18:00 }
        - day: { tz: America/Los_Angeles, days: [ Mon, Tue, Wed, Thu, Fri ] }
        - not: { date: { tz: America/Los_Angeles, dates: [ 2020-01-01, 2020-01-20, 2020-02-17, 2020-05-25, 2020-07-04, 2019-09-02, 2019-11-28, 2019-11-29, 2019-12-25 ] } }
        then:
          #literal: { text: "Due to the holidays, we have a small crew. Someone in office will respond ASAP." }
          literalmap:
            from:
              pairist:
                team: pivotal-docs-core
                track: "Interrupt"
            users:
              Miranda: U763PAYEN
              Severine: U0CPKDN2X
              Chloe: U7K1YTPC2
              Ollie: UERDYAJG7
              Paul: U0G5UH65U
              Max: U03BK5KEJ
              Viktoryia: U4R6DCSNT
              Paige: UDB1WVB7G
              Melinda: U24FQ4QUB
              Jane: U0NHJADU7
              Ramia: UB9M3GCTF
  options:
    empty_message: Sorry, no interrupt is available right now. The community may be able to help, or feel free to try again during the hours of 9am to 6pm Pacific Time.
